name: CI

on: [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build & Test
      run: |
        docker-compose up --build --detach
        echo "Built"
        docker exec cuede_webserver_1 pipenv run bash -c 'cd src && python manage.py test'
