name: CI

on: [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build & Test
      run: |
        docker-compose up --build --detach
        ./run_tests.sh
